useFMTitle: true
useNoteTitleForLink: true
noLegacyNoteRef: true
mermaid: true
useKatex: true
usePrettyRefs: true
dev:
    previewV2Enabled: false
    enablePreviewV2: true
site:
    copyAssets: true
    siteHierarchies:
        - root
    siteRootDir: docs
    usePrettyRefs: true
    title: Animals as Objects
    description: Animals as Objects knowledge base and authoring tool.
    duplicateNoteBehavior:
        action: useVault
        payload:
            - vault
    siteLastModified: true
    gh_edit_branch: main
version: 3
commands:
    lookup:
        note:
            selectionMode: extract
            confirmVaultOnCreate: false
            leaveTrace: false
    randomNote: {}
    insertNote:
        initialValue: templates
    insertNoteLink:
        aliasMode: none
        enableMultiSelect: false
    insertNoteIndex:
        enableMarker: false
workspace:
    dendronVersion: 0.67.1
    vaults:
        -
            fsPath: vault
    journal:
        dailyDomain: daily
        name: journal
        dateFormat: y.MM.dd
        addBehavior: childOfDomain
    scratch:
        name: scratch
        dateFormat: y.MM.dd.HHmmss
        addBehavior: asOwnDomain
    graph:
        zoomSpeed: 1
    enableAutoCreateOnDefinition: false
    enableXVaultWikiLink: false
    enableRemoteVaultInit: false
    workspaceVaultSyncMode: noCommit
    enableAutoFoldFrontmatter: true
    maxPreviewsCached: 10
    maxNoteLength: 204800
    enableUserTags: true
    enableHashTags: true
    task:
        name: ''
        dateFormat: ''
        addBehavior: childOfCurrent
        statusSymbols:
            '': ' '
            wip: w
            done: x
            assigned: a
            moved: m
            blocked: b
            delegated: l
            dropped: d
            pending: 'y'
        prioritySymbols:
            H: high
            M: medium
            L: low
        todoIntegration: false
        createTaskSelectionType: selection2link
