backend:
  name: github
  base_url: http://116.203.68.230:3000
  site_domain: animalsasobjects.org
  repo: trust-mfn-berlin/animals-as-objects
  branch: content-creation

media_folder: vault/images
public_folder: /images

collections:
  - name: "dendron"
    label: "Dendron"
    folder: "vault"
    format: "frontmatter"
    create: false
    view_filters:
      - label: themes
        field: tao_type
        pattern: 'theme'
      - label: materials
        field: tao_type
        pattern: 'material'
      - label: stories
        field: tao_type
        pattern: 'story'
      - label: Is Archived
        field: archived
        pattern: true
      - label: Is Not Archived
        field: archived
        pattern: false|undefined
    view_groups:
      - label: type
        field: tao_type
      - label: author
        field: author
      - label: Archived
        field: archived
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title DE", name: "title_de", widget: "string" }
      - { label: "Created", name: "created", widget: "number" }
      - { label: "Updated", name: "updated", widget: "number" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "DOI", name: "doi", widget: "string", required: false, hint: "DOI number only z.B. 10.7479/qv3p-3619" }
      - label: "Translator(s)"
        name: "translators"
        widget: "object"
        collapsed: true
        required: false
        fields:
          - {label: "Translator DE to EN", name: "translator_de_en", hint: "translated from German into English by...", required: false, widget: "string"}
          - {label: "Translator EN to DE", name: "translator_en_de", hint: "translated from English into German by...", required: false, widget: "string"}
      - { label: "Description", name: "desc", widget: "string", hint: "30-50 words" }
      - { label: "Description DE", name: "desc_de", widget: "string", hint: "30-50 words" }
      - { label: "Short Description", name: "short_desc", widget: "string", hint: "3-10 words" }
      - { label: "Short Description DE", name: "short_desc_de", widget: "string", hint: "3-10 words" }
      - label: "Cover image"
        name: "cover_image"
        widget: "object"
        collapsed: true
        allow_multiple: false
        required: false
        fields:
          - { label: "Image", name: "image", required: false, widget: "image"}
          - { label: "Description", hint: "for SEO and accessibility purposes", name: "alt", required: false, widget: "string"}
      - { label: "Colour Scheme", name: "colour_scheme", widget: "number", required: false, min: 0, max: 18, value_type: "int", hint: "number refers to colour scheme. https://dev.animalsasobjects.org/colours/" }
      - label: "TAO Content type"
        name: "tao_type"
        widget: "select"
        options: ["theme", "material", "story"]
      - { label: "Date start", name: "date_start", widget: "datetime", default: "", required: false }
      - { label: "Date end (if applicable)", name: "date_end", widget: "datetime", default: "", required: false }
      - { label: "Archived", name: "archived", widget: "boolean", hint: "Don't show this article", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: 'Map slide'
        name: 'map_slide'
        widget: 'list'
        collapsed: false
        fields:
          - label: 'Slide Title'
            name: 'title'
            widget: 'string'
          - label: 'Slide Title DE'
            name: 'title_de'
            widget: 'string'
          - label: 'Map slide caption'
            name: 'caption'
            widget: 'string'
          - label: 'Map slide caption DE'
            name: 'caption_de'
            widget: 'string'
          - label: "Caption image"
            name: "caption_image"
            widget: "object"
            collapsed: true
            allow_multiple: false
            required: false
            fields:
              - { label: "Image", name: "src", required: false, widget: "image"}
              - { label: "Description", hint: "for SEO and accessibility purposes", name: "alt", required: false, widget: "string"}
          - label: 'Map image'
            name: 'map_image'
            widget: 'image'
          - label: 'Map image DE'
            name: 'map_image_de'
            widget: 'image'
            hint: 'if labels are needed in DE use this field'
            required: false
  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page EN"
        name: "about_en"
        file: "vault/netlify/about_en.md"
        format: "frontmatter"
        fields:
          - {label: Title EN, name: title, widget: string}
          - {label: body, name: body, widget: markdown}
      - label: "About Page DE"
        name: "about_de"
        file: "vault/netlify/about_de.md"
        format: "frontmatter"
        fields:
          - {label: Title DE, name: title, widget: string}
          - {label: body, name: body, widget: markdown}
      - label: "Imprint EN"
        name: "imprint_en"
        file: "vault/netlify/imprint_en.md"
        format: "frontmatter"
        fields:
          - {label: Title EN, name: title, widget: string}
          - {label: body, name: body, widget: markdown}
      - label: "Imprint DE"
        name: "imprint_de"
        file: "vault/netlify/imprint_de.md"
        format: "frontmatter"
        fields:
          - {label: Title DE, name: title, widget: string}
          - {label: body, name: body, widget: markdown}
      - label: "Data Policy EN"
        name: "datapolicy_en"
        file: "vault/netlify/datapolicy_en.md"
        format: "frontmatter"
        fields:
          - {label: Title EN, name: title, widget: string}
          - {label: body, name: body, widget: markdown}
      - label: "Datenschutz DE"
        name: "datapolicy_de"
        file: "vault/netlify/datapolicy_de.md"
        format: "frontmatter"
        fields:
          - {label: Title DE, name: title, widget: string}
          - {label: body, name: body, widget: markdown}
      - label: "Route introduction text EN"
        name: "route_intro_en"
        file: "vault/netlify/route_intro_en.md"
        format: "frontmatter" 
        fields:
          - {label: body, name: body, widget: markdown}
      - label: "Route introduction text DE"
        name: "route_intro_de"
        file: "vault/netlify/route_intro_de.md"
        format: "frontmatter"
        fields:
          - {label: body, name: body, widget: markdown}

  - name: "curated_path"
    label: "Curated route"
    folder: "vault/netlify/pathways"
    editor:
      preview: false
    create: true
    fields:
      - {label: "Pathway Title EN", name: "title", widget: "string"}
      - {label: "Title DE", name: "title_de", widget: "string"}
      - {label: "Date Published", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - label: "Author bio"
        name: "author_bio"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Author Bio EN", name: author_bio_en, widget: string}
          - {label: "Author Bio DE", name: author_bio_de, widget: string}
      - label: "Introduction"
        name: "into_text"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Intro Text EN", name: text_en, widget: string}
          - {label: "Intro Text DE", name: text_de, widget: string}
      - label: 'Connected articles'
        name: 'articles'
        widget: 'list'
        collapsed: false
        fields:
          - label: 'Connected note'
            name: 'article'
            widget: 'relation'
            collection: 'dendron'
            display_fields: ['title']
            search_fields: ['title', 'title_de', 'author', 'tao_type', 'body']
            value_field: '{{slug}}'
      - label: "PDF collection"
        name: "pdf"
        hint: ".zip file with PDFs"
        widget: "file"