backend:
  name: github
  base_url: http://116.203.68.230:3000
  site_domain: animalsasobjects.org
  repo: trust-mfn-berlin/animals-as-objects
  branch: master

media_folder: vault/images
public_folder: /images

collections:
  - name: "dendron"
    label: "Dendron"
    folder: "vault"
    format: "frontmatter"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title DE", name: "title_de", widget: "string" }
      - { label: "Created", name: "created", widget: "number" }
      - { label: "Updated", name: "updated", widget: "number" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "desc", widget: "string" }
      - { label: "Description DE", name: "desc_de", widget: "string" }
      - {
          label: "Cover image",
          name: "cover_image",
          widget: "image",
          allow_multiple: false,
          required: false,
        }
      - label: "TAO Content type"
        name: "tao_type"
        widget: "select"
        options: ["theme", "material", "story"]
      - { label: "Published", name: "published", widget: "boolean" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page EN"
        name: "about_en"
        file: "vault/netlify/about_en.md"
        format: "frontmatter"
        fields:
          - {label: Title EN, name: title, widget: string}
          - {label: body, name: body, widget: markdown}
      - label: "About Page DE"
        name: "about_de"
        file: "vault/netlify/about_de.md"
        format: "frontmatter"
        fields:
          - {label: Title DE, name: title, widget: string}
          - {label: body, name: body, widget: markdown}
      - label: "Imprint EN"
        name: "imprint_en"
        file: "vault/netlify/imprint_en.md"
        format: "frontmatter"
        fields:
          - {label: Title EN, name: title, widget: string}
          - {label: body, name: body, widget: markdown}
      - label: "Imprint DE"
        name: "imprint_de"
        file: "vault/netlify/imprint_de.md"
        format: "frontmatter"
        fields:
          - {label: Title DE, name: title, widget: string}
          - {label: body, name: body, widget: markdown}
      - label: "Data Policy EN"
        name: "datapolicy_en"
        file: "vault/netlify/datapolicy_en.md"
        format: "frontmatter"
        fields:
          - {label: Title EN, name: title, widget: string}
          - {label: body, name: body, widget: markdown}
      - label: "Datenschutz DE"
        name: "datapolicy_de"
        file: "vault/netlify/datapolicy_de.md"
        format: "frontmatter"
        fields:
          - {label: Title DE, name: title, widget: string}
          - {label: body, name: body, widget: markdown}
  - name: "curated_path"
    label: "Curated pathway"
    folder: "vault/netlify/pathways"
    editor:
      preview: false
    create: true
    fields:
      - {label: "Pathway Title EN", name: "title", widget: "string"}
      - {label: "Title DE", name: "title_de", widget: "string"}
      - {label: "Date Published", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - label: "Author bio"
        name: "author_bio"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Author Bio EN", name: author_bio_en, widget: markdown}
          - {label: "Author Bio DE", name: author_bio_de, widget: markdown}
      - label: "Introduction"
        name: "into_text"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Intro Text EN", name: text_en, widget: markdown}
          - {label: "Intro Text DE", name: text_de, widget: markdown}
      - label: 'Connected notes'
        name: 'notes'
        widget: 'list'
        collapsed: false
        fields:
          - label: 'Connected note'
            name: 'note'
            widget: 'relation'
            collection: 'dendron'
            display_fields: ['title']
            search_fields: ['title', 'title_de', 'author', 'tao_type', 'body']
            value_field: 'id'
      
